import "../styles/globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { AppProps } from "next/app";
import {
  colors,
  CssBaseline,
  Experimental_CssVarsProvider,
  ThemeProvider,
  useTheme,
} from "@mui/material";
import { DefaultLayout } from "../components/Layouts";
import { Fragment } from "react";
import Head from "next/head";
import { theme } from "../components/theme";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Experimental_CssVarsProvider theme={theme}>
        <DefaultLayout>
          <CssBaseline></CssBaseline>
          <Component {...pageProps} />
        </DefaultLayout>
      </Experimental_CssVarsProvider>
    </Fragment>
  );
}
